# Generated by Django 6.0.5 on 2026-05-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
